interface Env{ASSETS:{fetch(request:Request):Promise<Response>};AI:{run(model:string,input:Record<string,unknown>):Promise<unknown>}}

type ScanBody={imageDataUrl?:unknown;context?:{hst?:unknown;soil?:unknown;fertilization?:unknown;symptoms?:unknown}};
const MODEL='@cf/meta/llama-4-scout-17b-16e-instruct';
const MAX_BASE64_CHARS=7_000_000;
const ALLOWED_MIME=new Set(['image/jpeg','image/png','image/webp']);
const STATUSES=['Sehat','Perlu Diamati','Perlu Pemeriksaan','Data Belum Cukup'] as const;
const QUALITIES=['good','fair','poor'] as const;

function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}})}
function validateImage(v:unknown):v is string{if(typeof v!=='string'||v.length<30||v.length>MAX_BASE64_CHARS)return false;const m=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(v);return !!m&&ALLOWED_MIME.has(m[1])}
function list(v:unknown,max=6){return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string').map(x=>x.trim().slice(0,220)).filter(Boolean).slice(0,max):[]}
function conf(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):0}
function text(v:unknown,max=600){return typeof v==='string'?v.trim().slice(0,max):''}
function prompt(body:ScanBody){const c=body.context&&typeof body.context==='object'?body.context:{};const s=Array.isArray(c.symptoms)?c.symptoms.filter((x):x is string=>typeof x==='string').slice(0,8):[];return[`Anda adalah Cabeku, pemeriksaan visual awal tanaman cabai untuk petani Indonesia.`,`Analisis FOTO yang diberikan sebagai sumber utama. Jangan hanya mengikuti checklist.`,`Hanya tuliskan ciri visual yang benar-benar terlihat. Jangan mendiagnosis penyakit, jangan memastikan patogen, dan jangan memberi dosis pupuk atau pestisida.`,`Gunakan tepat satu status: ${STATUSES.join(', ')}. Gunakan Data Belum Cukup bila foto buram, gelap, objek tidak jelas, atau bagian penting tidak terlihat.`,`Buat satu KESIMPULAN singkat 1-2 kalimat berdasarkan foto.`,`Jangan gunakan markdown atau blok kode. Kembalikan JSON objek tunggal saja dengan field photo_quality,status,confidence,conclusion,observations,caution,next_steps.`,`photo_quality harus salah satu dari: good, fair, poor. confidence harus angka 0-100.`,`Data pendukung: HST=${String(c.hst??'—')}; tanah=${String(c.soil??'—')}; pupuk=${String(c.fertilization??'—')}; gejala pengguna=${s.join(', ')||'—'}.`].join('\n')}
function extract(result:unknown):string{if(typeof result==='string')return result;if(!result||typeof result!=='object')return'';const r=result as Record<string,unknown>;const direct=['response','result','text','output_text','content'];for(const key of direct){const value=r[key];if(typeof value==='string'&&value.trim())return value;if(value&&typeof value==='object'){const nested=extract(value);if(nested)return nested}}const choices=r.choices;if(Array.isArray(choices)){for(const choice of choices){const nested=extract(choice);if(nested)return nested}}return''}
function parseText(raw:string):unknown{const cleaned=raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');for(const candidate of [cleaned,raw]){try{return JSON.parse(candidate)}catch{}}const m=cleaned.match(/\{[\s\S]*\}/);if(!m)return null;try{return JSON.parse(m[0])}catch{return null}}
function review(value:unknown){if(!value||typeof value!=='object')return null;const o=value as Record<string,unknown>;const statusValue=o.status??o.Status??o.overall_status;const qualityValue=o.photo_quality??o.photoQuality??o.quality;const confidenceValue=o.confidence??o.confidence_score??o.confidenceScore;const status=typeof statusValue==='string'&&STATUSES.includes(statusValue as typeof STATUSES[number])?statusValue as typeof STATUSES[number]:null;const quality=typeof qualityValue==='string'&&QUALITIES.includes(qualityValue as typeof QUALITIES[number])?qualityValue as typeof QUALITIES[number]:null;if(!status||!quality)return null;return{photo_quality:quality,status,confidence:conf(confidenceValue),conclusion:text(o.conclusion??o.summary,600)||'Belum ada kesimpulan yang cukup kuat dari foto.',observations:list(o.observations??o.visual_observations),caution:text(o.caution??o.warning,500)||'Hasil ini adalah pemeriksaan visual awal dan bukan diagnosis penyakit.',next_steps:list(o.next_steps??o.nextSteps,5)}}
async function scan(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'}});if(request.method!=='POST')return json({error:'Method not allowed'},405);let body:ScanBody;try{body=await request.json() as ScanBody}catch{return json({error:'Format data tidak valid.'},400)}if(!validateImage(body.imageDataUrl))return json({error:'Foto tidak valid. Gunakan JPG, PNG, atau WebP.'},400);try{const result=await env.AI.run(MODEL,{messages:[{role:'user',content:prompt(body)}],image:body.imageDataUrl,max_tokens:900,temperature:0.1});const raw=extract(result);if(!raw){console.error('Cabeku AI empty response',JSON.stringify(result).slice(0,1200));return json({error:'AI tidak mengembalikan respons.'},502)}const parsed=parseText(raw);if(!parsed){console.error('Cabeku AI unparsable response',raw.slice(0,1200));return json({error:'AI merespons, tetapi format kesimpulannya tidak dapat dibaca.'},502)}const out=review(parsed);if(!out){console.error('Cabeku AI schema mismatch',raw.slice(0,1200));return json({error:'AI merespons, tetapi struktur hasilnya tidak sesuai format Cabeku.'},502)}if(out.photo_quality==='poor'){out.status='Data Belum Cukup';out.confidence=Math.min(out.confidence,45);out.conclusion='Foto belum cukup jelas untuk menarik kesimpulan visual yang bertanggung jawab.';out.next_steps=['Ambil foto dengan cahaya cukup dan fokus','Tampilkan daun, batang, dan buah bila ada']}return json({ok:true,review:out})}catch(e){const message=e instanceof Error?e.message:String(e);console.error('Cabeku AI error',message);return json({error:'Pemeriksaan AI gagal. Periksa Workers AI binding dan lihat Workers Logs untuk detail teknis.'},502)}}

async function serveCabeku(request:Request,env:Env){const assetRequest=new Request(new URL('/cabeku/index.html',request.url),request);const asset=await env.ASSETS.fetch(assetRequest);if(!asset.ok)return new Response('Cabeku page asset tidak ditemukan.',{status:404,headers:{'content-type':'text/plain; charset=utf-8'}});const source=await asset.text();const scripts=['/cabeku/multi-photo.js','/cabeku/reset-bridge.js'].filter(path=>!source.includes(path)).map(path=>`<script src="${path}" defer></script>`).join('');if(!scripts)return new Response(source,asset);const html=source.replace('</body>',`${scripts}</body>`);return new Response(html,{status:asset.status,statusText:asset.statusText,headers:asset.headers})}

export default{async fetch(request:Request,env:Env){const u=new URL(request.url);if(u.pathname==='/api/cabeku-scan')return scan(request,env);if(u.pathname==='/api/cabeku-health')return json({ok:true,service:'cabeku-ai',model:MODEL});if(u.pathname.startsWith('/api/'))return json({error:'API endpoint tidak ditemukan.'},404);if(['/serba-serbi/cabeku','/serba-serbi/cabeku/','/serba-serbi/cabeku/index.html','/cabeku','/cabeku/'].includes(u.pathname))return serveCabeku(request,env);return env.ASSETS.fetch(request)}} satisfies ExportedHandler<Env>;
