import { assessGrowth, growthReferenceMeta, type GrowthVariety, type GrowthMeasures } from "../functions/api/growth-engine";

type Env={ASSETS:{fetch(r:Request):Promise<Response>};AI:{run(model:string,input:Record<string,unknown>):Promise<unknown>}};
type Ctx={hst?:unknown;soil?:unknown;fertilization?:unknown;symptoms?:unknown;variety?:unknown;measurements?:unknown};
type Body={imageDataUrl?:unknown;imageDataUrls?:unknown;context?:Ctx};
type Review={photo_quality:"good"|"fair"|"poor";status:"Sehat"|"Perlu Diamati"|"Perlu Pemeriksaan"|"Data Belum Cukup";confidence:number;conclusion:string;observations:string[];caution:string;next_steps:string[]};
const MODEL="@cf/meta/llama-4-scout-17b-16e-instruct";
const RUNTIME="cabeku-worker-v6-vision-prompt-fix-2026-09-13";
const STATUSES=["Sehat","Perlu Diamati","Perlu Pemeriksaan","Data Belum Cukup"] as const;
const QUALITIES=["good","fair","poor"] as const;
const SCHEMA={type:"object",additionalProperties:false,properties:{photo_quality:{type:"string",enum:["good","fair","poor"]},status:{type:"string",enum:[...STATUSES]},confidence:{type:"number",minimum:0,maximum:100},conclusion:{type:"string"},observations:{type:"array",items:{type:"string"}},caution:{type:"string"},next_steps:{type:"array",items:{type:"string"}}},required:["photo_quality","status","confidence","conclusion","observations","caution","next_steps"]};
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","x-cabeku-runtime":RUNTIME}});
const clamp=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):0};
const asText=(v:unknown,n=600)=>typeof v==="string"?v.trim().slice(0,n):"";
const asList=(v:unknown,n=6)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string").map(x=>x.trim()).filter(Boolean).slice(0,n):[];
const parseJson=(v:unknown):unknown|null=>{if(v&&typeof v==="object")return v;if(typeof v!=="string")return null;const s=v.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();try{const p=JSON.parse(s);return typeof p==="string"?parseJson(p):p}catch{}for(let a=0;a<s.length;a++){if(s[a]!=="{")continue;let d=0,q=false,e=false;for(let i=a;i<s.length;i++){const c=s[i];if(q){if(e)e=false;else if(c==="\\")e=true;else if(c==='"')q=false;continue}if(c==='"'){q=true;continue}if(c==="{")d++;else if(c==='}'&&--d===0){try{return JSON.parse(s.slice(a,i+1))}catch{}break}}}return null};
function review(v:unknown,depth=0):Review|null{if(depth>8)return null;const p=parseJson(v);if(p==null)return null;if(Array.isArray(p)){for(const x of p){const r=review(x,depth+1);if(r)return r}return null}if(typeof p!=="object")return review(p,depth+1);const o=p as Record<string,unknown>;const status=o.status??o.Status??o.overall_status;const quality=o.photo_quality??o.photoQuality??o.quality;if(typeof status==="string"&&(STATUSES as readonly string[]).includes(status)&&typeof quality==="string"&&(QUALITIES as readonly string[]).includes(quality)){return{photo_quality:quality as Review["photo_quality"],status:status as Review["status"],confidence:clamp(o.confidence??o.confidence_score??o.confidenceScore),conclusion:asText(o.conclusion??o.summary??o.kesimpulan)||"Belum ada kesimpulan yang cukup kuat dari foto.",observations:asList(o.observations??o.visual_observations??o.pengamatan),caution:asText(o.caution??o.warning??o.catatan,500)||"Hasil ini adalah pemeriksaan visual awal dan bukan diagnosis penyakit.",next_steps:asList(o.next_steps??o.nextSteps??o.langkah_berikutnya,5)}}for(const k of ["review","result","response","output","data","content","message","json"]){if(k in o){const r=review(o[k],depth+1);if(r)return r}}for(const x of Object.values(o)){const r=review(x,depth+1);if(r)return r}return null}
const prompt=(c:Ctx|undefined,n:number)=>{const x=c??{};const s=Array.isArray(x.symptoms)?x.symptoms.filter((v):v is string=>typeof v==="string").join(", "):"—";return[`Anda adalah Cabeku, pemeriksaan visual awal tanaman cabai Indonesia.`,`Analisis foto tanaman yang diberikan. Jika ada lebih dari satu foto dalam satu request, perlakukan sebagai satu kasus.`,`Hanya tuliskan ciri yang benar-benar terlihat. Jangan mendiagnosis penyakit/patogen dan jangan memberi dosis pupuk/pestisida.`,`Gunakan status Sehat, Perlu Diamati, Perlu Pemeriksaan, atau Data Belum Cukup.`,`Jangan memilih Data Belum Cukup hanya karena HST, tanah, pupuk, atau gejala belum diisi. Gunakan Data Belum Cukup hanya jika foto/objek memang tidak cukup jelas untuk observasi visual.`,`Untuk foto yang jelas, berikan sekurang-kurangnya 1 observasi visual yang nyata dan confidence 1-100. Jangan menggunakan confidence 0 untuk foto yang jelas; 0 hanya untuk kegagalan nyata membaca kasus.`,`Nilai fase bibit/vegetatif boleh diberikan dari ciri visual tanpa mengarang HST.`,`Kembalikan JSON tunggal tanpa markdown dengan field photo_quality,status,confidence,conclusion,observations,caution,next_steps.`,`Konteks: jumlah foto=${n}; HST=${String(x.hst??"—")}; varietas=${String(x.variety??"—")}; tanah=${String(x.soil??"—")}; pupuk=${String(x.fertilization??"—")}; gejala=${s}.`].join("\n")};
const getImages=(b:Body)=>{const a=Array.isArray(b.imageDataUrls)?b.imageDataUrls:typeof b.imageDataUrl==="string"?[b.imageDataUrl]:[];return a.filter((x):x is string=>typeof x==="string").slice(0,5)};
const validImage=(v:string)=>/^data:image\/(?:jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v)&&v.length<=7_000_000;
async function ai(env:Env,c:Ctx|undefined,imgs:string[]){const base={prompt:prompt(c,imgs.length),image:imgs[0],max_tokens:900,temperature:.1,stream:false};try{const first=await env.AI.run(MODEL,{...base,guided_json:SCHEMA});const r=review(first);if(r)return r}catch(e){console.warn("Cabeku guided JSON failed",e instanceof Error?e.message:String(e))}const second=await env.AI.run(MODEL,base);const r=review(second);if(r)return r;throw new Error("CABEKU_AI_RESPONSE_UNPARSABLE")}
const growth=(c:Ctx|undefined)=>{const n=(v:unknown,m:number)=>{if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)&&x>=0&&x<=m?x:null};const vv=typeof c?.variety==="string"?c.variety:"unknown";const variety:GrowthVariety=vv==="rawit"||vv==="merah"||vv==="keriting"?vv:"unknown";const m=c?.measurements&&typeof c.measurements==="object"?c.measurements as Record<string,unknown>:{};return{hst:n(c?.hst,500),variety,measures:{heightCm:n(m.heightCm,500),canopyCm:n(m.canopyCm,500),leafCount:n(m.leafCount,1000),leafWidthCm:n(m.leafWidthCm,100)}}};
async function scan(req:Request,env:Env){if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":"*","access-control-allow-methods":"POST, OPTIONS","access-control-allow-headers":"Content-Type"}});if(req.method!=="POST")return response({error:"Method not allowed"},405);let body:Body;try{body=await req.json() as Body}catch{return response({error:"Format data tidak valid."},400)}const imgs=getImages(body);if(!imgs.length||imgs.some(x=>!validImage(x)))return response({error:"Foto tidak valid. Gunakan JPG, PNG, atau WebP."},400);try{const r=await ai(env,body.context,imgs);const visual=r.photo_quality==="poor"?{...r,status:"Data Belum Cukup" as const,confidence:Math.min(r.confidence,45),conclusion:"Foto belum cukup jelas untuk menarik kesimpulan visual yang bertanggung jawab.",next_steps:["Ambil foto dengan cahaya cukup dan fokus","Tampilkan satu tanaman utama"]}:r;const g=growth(body.context);const ga=assessGrowth(g.hst,g.variety,g.measures);return response({ok:true,runtime:RUNTIME,review:visual,growth:ga,audit:{engine:"cabeku-growth-engine-v1",reference:growthReferenceMeta(),benchmarkSource:ga.benchmark?.sourceId??null}})}catch(e){console.error("Cabeku scan error",e instanceof Error?e.message:String(e));return response({error:"Pemeriksaan AI gagal atau respons AI tidak dapat dibaca.",runtime:RUNTIME},502)}}
async function page(req:Request,env:Env){const r=await env.ASSETS.fetch(new Request(new URL("/cabeku/index.html",req.url),req));if(!r.ok)return new Response("Cabeku page asset tidak ditemukan.",{status:404});const s=await r.text();const add=["/cabeku/multi-photo.js","/cabeku/reset-bridge.js"].filter(x=>!s.includes(x)).map(x=>`<script src="${x}" defer></script>`).join("");return add?new Response(s.replace("</body>",`${add}</body>`),r):new Response(s,r)}
export default{async fetch(req:Request,env:Env){const u=new URL(req.url);if(u.pathname==="/api/cabeku-scan")return scan(req,env);if(u.pathname==="/api/cabeku-health")return response({ok:true,service:"cabeku",runtime:RUNTIME,model:MODEL,engine:"cabeku-growth-engine-v1"});if(u.pathname.startsWith("/api/"))return response({error:"API endpoint tidak ditemukan."},404);if(["/cabeku","/cabeku/","/cabeku/index.html","/serba-serbi/cabeku","/serba-serbi/cabeku/","/serba-serbi/cabeku/index.html"].includes(u.pathname))return page(req,env);return env.ASSETS.fetch(req)}} satisfies ExportedHandler<Env>;
