interface Env{ASSETS:{fetch(request:Request):Promise<Response>};AI:{run(model:string,input:Record<string,unknown>):Promise<unknown>}}

type ScanBody={imageDataUrl?:unknown;context?:{hst?:unknown;soil?:unknown;fertilization?:unknown;symptoms?:unknown}};
const MODEL='@cf/meta/llama-4-scout-17b-16e-instruct';
const MAX_BASE64_CHARS=7_000_000;
const ALLOWED_MIME=new Set(['image/jpeg','image/png','image/webp']);
const STATUSES=['Sehat','Perlu Diamati','Perlu Pemeriksaan','Data Belum Cukup'] as const;
const QUALITIES=['good','fair','poor'] as const;
const RESPONSE_SCHEMA={type:'object',properties:{photo_quality:{type:'string',enum:['good','fair','poor']},status:{type:'string',enum:['Sehat','Perlu Diamati','Perlu Pemeriksaan','Data Belum Cukup']},confidence:{type:'number',minimum:0,maximum:100},conclusion:{type:'string'},observations:{type:'array',items:{type:'string'}},caution:{type:'string'},next_steps:{type:'array',items:{type:'string'}}},required:['photo_quality','status','confidence','conclusion','observations','caution','next_steps']};

function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}})}
function validateImage(v:unknown):v is string{if(typeof v!=='string'||v.length<30||v.length>MAX_BASE64_CHARS)return false;const m=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(v);return !!m&&ALLOWED_MIME.has(m[1])}
function list(v:unknown,max=6){return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string').map(x=>x.trim().slice(0,220)).filter(Boolean).slice(0,max):[]}
function conf(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):0}
function text(v:unknown,max=600){return typeof v==='string'?v.trim().slice(0,max):''}
function prompt(body:ScanBody){const c=body.context&&typeof body.context==='object'?body.context:{};const s=Array.isArray(c.symptoms)?c.symptoms.filter((x):x is string=>typeof x==='string').slice(0,8):[];return[`Anda adalah Cabeku, pemeriksaan visual awal tanaman cabai untuk petani Indonesia.`,`Analisis FOTO sebagai sumber utama. Gunakan data HST/tanah/pupuk hanya sebagai konteks pendukung.`,`Hanya tuliskan ciri visual yang benar-benar terlihat. Jangan mendiagnosis penyakit, jangan memastikan patogen, dan jangan memberi dosis pupuk atau pestisida.`,`Gunakan tepat satu status: ${STATUSES.join(', ')}. Gunakan Data Belum Cukup bila objek tidak jelas, foto gelap, atau bagian penting tidak terlihat.`,`Buat kesimpulan singkat 1-2 kalimat.`,`Kembalikan objek JSON tunggal dengan field: photo_quality,status,confidence,conclusion,observations,caution,next_steps.`,`photo_quality: good|fair|poor. confidence: angka 0-100. observations dan next_steps harus array string.`,`Jangan menambahkan markdown, code fence, atau teks di luar objek JSON.`,`Data pendukung: HST=${String(c.hst??'—')}; tanah=${String(c.soil??'—')}; pupuk=${String(c.fertilization??'—')}; gejala pengguna=${s.join(', ')||'—'}.`].join('\n')}

async function extract(value:unknown,depth=0):Promise<string>{if(depth>8||value==null)return'';if(typeof value==='string')return value.trim();if(typeof value==='number'||typeof value==='boolean')return String(value);if(typeof ReadableStream!=='undefined'&&value instanceof ReadableStream){try{return(await new Response(value).text()).trim()}catch{return''}}if(Array.isArray(value)){for(const item of value){const found=await extract(item,depth+1);if(found)return found}return''}if(typeof value==='object'){const r=value as Record<string,unknown>;for(const key of ['response','result','text','output_text','content','message','output']){if(!(key in r))continue;const found=await extract(r[key],depth+1);if(found)return found}for(const [key,nested] of Object.entries(r)){if(['usage','request_id','errors','success'].includes(key))continue;const found=await extract(nested,depth+1);if(found)return found}}return''}
function parseText(raw:string):unknown{const trimmed=raw.trim();const cleaned=trimmed.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();for(const candidate of [cleaned,trimmed]){try{return JSON.parse(candidate)}catch{}}const matches=[...cleaned.matchAll(/\{[\s\S]*?\}/g)];for(const match of matches.reverse()){try{return JSON.parse(match[0])}catch{}}return null}
function unwrap(value:unknown):unknown{if(!value||typeof value!=='object')return value;const o=value as Record<string,unknown>;if(o.review&&typeof o.review==='object')return o.review;if(o.result&&typeof o.result==='object')return o.result;if(o.response&&typeof o.response==='object')return o.response;return value}
function review(value:unknown){const unwrapped=unwrap(value);if(!unwrapped||typeof unwrapped!=='object')return null;const o=unwrapped as Record<string,unknown>;const statusValue=o.status??o.Status??o.overall_status;const qualityValue=o.photo_quality??o.photoQuality??o.quality;const confidenceValue=o.confidence??o.confidence_score??o.confidenceScore;const status=typeof statusValue==='string'&&STATUSES.includes(statusValue as typeof STATUSES[number])?statusValue as typeof STATUSES[number]:null;const quality=typeof qualityValue==='string'&&QUALITIES.includes(qualityValue as typeof QUALITIES[number])?qualityValue as typeof QUALITIES[number]:null;if(!status||!quality)return null;return{photo_quality:quality,status,confidence:conf(confidenceValue),conclusion:text(o.conclusion??o.summary??o.kesimpulan,600)||'Belum ada kesimpulan yang cukup kuat dari foto.',observations:list(o.observations??o.visual_observations??o.pengamatan),caution:text(o.caution??o.warning??o.catatan,500)||'Hasil ini adalah pemeriksaan visual awal dan bukan diagnosis penyakit.',next_steps:list(o.next_steps??o.nextSteps??o.langkah_berikutnya,5)}}

async function runAI(env:Env,body:ScanBody){
  const base={messages:[{role:'user',content:prompt(body)}],image:body.imageDataUrl,max_tokens:900,temperature:0.1,stream:false};
  const structured={...base,guided_json:RESPONSE_SCHEMA};
  try{
    const first=await env.AI.run(MODEL,structured);
    const firstText=await extract(first);
    if(firstText)return firstText;
    console.warn('Cabeku guided_json returned empty output; retrying without guided_json');
  }catch(error){console.warn('Cabeku guided_json failed; retrying without guided_json',error instanceof Error?error.message:String(error))}
  const fallback=await env.AI.run(MODEL,base);
  return extract(fallback);
}

async function scan(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'}});if(request.method!=='POST')return json({error:'Method not allowed'},405);let body:ScanBody;try{body=await request.json() as ScanBody}catch{return json({error:'Format data tidak valid.'},400)}if(!validateImage(body.imageDataUrl))return json({error:'Foto tidak valid. Gunakan JPG, PNG, atau WebP.'},400);try{const raw=await runAI(env,body);if(!raw){console.error('Cabeku AI empty response');return json({error:'AI tidak mengembalikan respons. Pemeriksaan Vision belum menghasilkan teks.'},502)}const parsed=parseText(raw);if(!parsed){console.error('Cabeku AI unparsable response',raw.slice(0,1800));return json({error:'AI merespons, tetapi format JSON tidak dapat dibaca.'},502)}const out=review(parsed);if(!out){console.error('Cabeku AI schema mismatch',raw.slice(0,1800));return json({error:'AI merespons, tetapi struktur hasilnya tidak sesuai format Cabeku.'},502)}if(out.photo_quality==='poor'){out.status='Data Belum Cukup';out.confidence=Math.min(out.confidence,45);out.conclusion='Foto belum cukup jelas untuk menarik kesimpulan visual yang bertanggung jawab.';out.next_steps=['Ambil foto dengan cahaya cukup dan fokus','Tampilkan daun, batang, dan buah bila ada']}return json({ok:true,review:out})}catch(e){const message=e instanceof Error?e.message:String(e);console.error('Cabeku AI error',message);return json({error:'Pemeriksaan AI gagal. Periksa Workers AI binding dan lihat Workers Logs untuk detail teknis.'},502)}}

async function serveCabeku(request:Request,env:Env){const assetRequest=new Request(new URL('/cabeku/index.html',request.url),request);const asset=await env.ASSETS.fetch(assetRequest);if(!asset.ok)return new Response('Cabeku page asset tidak ditemukan.',{status:404,headers:{'content-type':'text/plain; charset=utf-8'}});const source=await asset.text();const scripts=['/cabeku/multi-photo.js','/cabeku/reset-bridge.js'].filter(path=>!source.includes(path)).map(path=>`<script src="${path}" defer></script>`).join('');if(!scripts)return new Response(source,asset);const html=source.replace('</body>',`${scripts}</body>`);return new Response(html,{status:asset.status,statusText:asset.statusText,headers:asset.headers})}

export default{async fetch(request:Request,env:Env){const u=new URL(request.url);if(u.pathname==='/api/cabeku-scan')return scan(request,env);if(u.pathname==='/api/cabeku-health')return json({ok:true,service:'cabeku-ai',model:MODEL});if(u.pathname.startsWith('/api/'))return json({error:'API endpoint tidak ditemukan.'},404);if(['/serba-serbi/cabeku','/serba-serbi/cabeku/','/serba-serbi/cabeku/index.html','/cabeku','/cabeku/'].includes(u.pathname))return serveCabeku(request,env);return env.ASSETS.fetch(request)}} satisfies ExportedHandler<Env>;
